main:
  action_dim: 1

wandb:
  use: true
  project: test
  name: test-ppo-${main.action_dim}-actions

ppo:
  n_latent_var: 128
  lr: 0.001
  betas: [0.9, 0.999]
  K_epochs: 4
  eps_clip: 0.2
  gamma: 0.99
  max_action: 1
  action_std: 0.5

env:
  scene_path: test.ttt
  headless: True
  state: low
  state_size: all

icm:
  embedding_size: 32
  loss_buffer_len: 200
  lr: 0.0001