main:
  max_timesteps: 250000
  train_each: 100
  train: True
  n_trials: 5
  action_dim: 3

wandb:
  use: False
  project: collision
  name: test

ppo:
  n_latent_var: 256
  lr: 0.002
  betas: [0.9, 0.999]
  K_epochs: 4
  eps_clip: 0.2
  gamma: 0.99
  max_action: 0.1
  action_std: 0.5

env:
  scene_path: base.ttt
  headless: True
  state: low
  state_size: all

log:
  name: ???

mp:
  n_procs: 3
