main:
  max_timesteps: 100000
  train_each: 100
  train: True
  n_trials: 5
  action_dim: 7

wandb:
  use: False
  project: collision
  name: test

ppo:
  n_latent_var: 1024
  lr: 0.0001
  betas: [0.9, 0.999]
  K_epochs: 4
  eps_clip: 0.2
  gamma: 0.99
  max_action: 1
  action_std: 0.5

env:
  scene_path: base.ttt
  headless: True
  state: low
  state_size: all
  action_dim: ${main.action_dim}

log:
  name: ???

icm:
  embedding_size: 200

MMModel:
  prop_dim: 14
  tac_dim: 15
  audio_dim: 4
  latent_dim: 200
  lstm_hidden_size: 20
  lstm_layers: 2

mp:
  n_procs: 6