main:
  env_name: 'reach_target-state-v0'
  max_timesteps: 100000
  train_each: 100
  video_length: 1000
  video_name: "vid/recording_"
  video_format: ".mp4"

wandb:
  use: False
  project: curious
  name: test

ppo:
  n_latent_var: 64
  lr: 0.002
  betas: [0.9, 0.999]
  K_epochs: 4
  eps_clip: 0.2
  gamma: 0.99