main:
  env_name: 'reach_target-state-v0'
  max_timesteps: 10000
  train_each: 100

wandb:
  use: False
  project: curious
  name: test

ppo:
  n_latent_var: 64
  lr: 0.002
  betas: [0.9, 0.999]
  K_epochs: 4
  eps_clip: 0.2
  gamma: 0.99