main:
  env_name: reach_target-state-v0
  
ppo:
  n_latent_var: 512
  lr: 0.002
  betas: [0.9, 0.999]
  K_epochs: 6
  eps_clip: 0.2
  gamma: 0.99
  max_action: 1

wandb:
  use: False
  project: test
  name: test