main:
  n_steps: 5000000
  train_each: 500
  train: True
  record_pc: False
  gpu: False
  save_state: False
  checkpoint: ""
  save_every: 100000
  reset: False

ppo:
  n_latent_var: 128
  lr: 0.0003
  betas: [0.9, 0.999]
  K_epochs: 4
  eps_clip: 0.3
  gamma: 0.95
  max_action: 1
  action_std: 0.5

env:
  scene_path: base.ttt
  headless: True
  state: prop,tac
  action_dim: 7
  torch_seed: 42
  np_seed: 42

wandb:
  project: test
  name: testname
  dryrun: True

icm:
  embedding_size: 256
  alpha: 0.001
  n_layers: 2
  lr: 0.0001
  standardize_loss: False

mp:
  n_procs: 1
