main:
  n_steps: 2000
  train_each: 500
  train: True
  record_pc: False
  gpu: False
  save_state: False
  checkpoint: False
  save_every: 100000
  reset: False

  tag: lorey-batcher

  iv_train_steps: 25000
  with_im: True
  dataset_len: 1000000
  n_goals: 20
  addrank: 0
  bsize: 1000
  policy: "td3"

ppo:
  alpha: 0.2
  n_latent_var: 128
  lr: 0.0005
  betas: [0.9, 0.999]
  K_epochs: 4
  eps_clip: 0.3
  gamma: 0.6
  max_action: 1
  action_std: 0.7

td3:
  expl_noise: 0.2
  tau: 0.005
  policy_noise: 0.2
  noise_clip: 0.5
  policy_freq: 2
  max_action: 1
  discount: 0.99
  alpha: 0.2
  burn_in: 50000

env:
  scene_path: base.ttt
  headless: True
  state: prop
  action_dim: 7
  torch_seed: 1
  np_seed: 1
  suppress_stdout: True

wandb:
  project: off-policy
  name: test
  group: ${wandb.name}

icm:
  embedding_size: 7
  alpha: 0.001
  n_layers: 2
  lr: 0.001
  standardize_loss: False

mp:
  n_procs: 1
