main:
  n_steps: 500
  train_each: 500
  train: True
  record_pc: False
  gpu: False
  save_state: False
  checkpoint: False
  save_every: 100000
  reset: False

  iv_train_steps: 25000
  with_im: True

ppo:
  alpha: 0.2
  n_latent_var: 128
  lr: 0.0001
  betas: [0.9, 0.999]
  K_epochs: 4
  eps_clip: 0.3
  gamma: 0.8
  max_action: 1
  action_std: 0.5

env:
  scene_path: base.ttt
  headless: True
  state: prop
  action_dim: 7
  torch_seed: 42069
  np_seed: 42069

wandb:
  project: test
  name: ""
  group: ${wandb.name}

icm:
  embedding_size: 256
  alpha: 0.001
  n_layers: 2
  lr: 0.001
  standardize_loss: False

mp:
  n_procs: 1
